### PR TITLE
Consolidate configuration options

### PR DESCRIPTION
**Pull request by johanneskonst**
moved all pdf and xls configuration into the default config.*.php files.
am now using the sample file as blueprint for available settings
had to fiddle with the constants to get no BC breaks.
only drawback is that _when_ people've used the pdf.inc and/or xls.inc files those settings are not automatically used.
but that's something we can fix in the upgrade.php script

### CODE REVIEW

**Review by copperhead57 — COMMENTED** [review]
@johanneskonst a few comments

1. when running with no change to config.inc receive code 500 - as you say can be fixed in upgrade.php.
2. $config['pdf'] = 0;  and $config['xls'] = 0; i would set to 1 as they are in original files and includes are active in original config.sample.
3. For pdf maybe we need to add remarks to all the settings with the recommended defaults as i am sure users will play with these and if issues will need to reset. i know they could just copy from sample but will they realize that the values are in there.
4. Testing so far has found no issues

**Comment by johanneskonst** [comment]
@copperhead57 any more info on why you get the 500? only reason i can think of this quickly is the define() statements in config.inc but i thought i mitigated that...
2. agree, required code is in repo already (or will be in release) so enabling those by default would do no harm
3. agreed, all config options need more documentation, will amend soon
4. 👍🏼

**Comment by copperhead57** [comment]
@johanneskonst i am stumped why 500. nothing  is showing in php error log. maybe that the 2 included statements for xls and php are not found.

**Comment by johanneskonst** [comment]
Ah, yes, doing a require_once on a non-existent file might fail hard indeed. But people already having a config.inc are going to do an upgrade and probably still have pdf.inc and xls.inc in place so hopefully no error there. I'll put that in install/upgrade.php lateron.

**Comment by copperhead57** [comment]
definitely - have reproduced the 500 by including one of the require_once on a non-existent file

**Comment by copperhead57** [comment]
I am still getting the 500 on the old config.inc
is not being modified with new options and deletion of deleted files

**Comment by johanneskonst** [comment]
Are you getting the 500 because of the missing files (pdf.inc / xls.inc) or is it something else? I havent done any work on the update process yet, you want me to focus on that first?Message ID: ***@***.***>

**Comment by copperhead57** [comment]
yes because of pdf,inc and xls.inc missing.
i have updated my config.inc in-line with sample and all is fine
my only concern is for people that upgrade to new master without realising that they need to change their config.inc and get 500 error and issues maybe raised.

**Pull request merged**
