### PR TITLE
Fix tab imdb online not formatting correctly

### PR DESCRIPTION
**Pull request by kec2**

### CODE REVIEW

**Comment by andig** [comment]
@kec2 your PRs are really unmergeable as they change every single file often only spacing and formatting. Is it possible to break them down into manageable pieces?

**Comment by kec2** [comment]
Sure.

I tried to make a pull-request on one branch only.  But it seams that Github did it with all changes ever made in my fork.


Hilsen

Klaus Christiansen


________________________________

**Comment by kec2** [comment]
Are you sure you want me to clean up this pull-request? 
It seams that you already incorporated the important part. 
Maybe this pull-request should just be deleted.

**Comment by andig** [comment]
Seems your branch for this PR was not started from clean master. No problem, please feel free to open new ones if needed- THANKS!

**Pull request closed without merging**
